services:
    dev.validate_schema:
        class: steevanb\DevBundle\Service\ValidateSchemaService
        arguments: [ '@doctrine', '@dev.session_cache' ]

    dev.session_cache:
        class: steevanb\DevBundle\Cache\SessionCache
        arguments: [ '@session', '@kernel' ]
